package com.PortfolioHeatmap.models;

/**
 * Represents a portfolio entry in the application, linking a user to a stock with details
 * about shares owned and cost basis. This class is a JPA entity mapped to the "portfolio" table
 * in the database.
 * 
 * @author [Marvel Bana]
 */
import jakarta.persistence.*;
import lombok.Getter;
import lombok.Setter;
import java.math.BigDecimal;

@Entity
@Getter
@Setter
@Table(name = "portfolio")
public class Portfolio {
    // Primary key for the portfolio entry, auto-generated by the database.
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    // The user who owns this portfolio entry, linked via a foreign key.
    // Cannot be null, as each portfolio entry must be associated with a user.
    @ManyToOne
    @JoinColumn(name = "user_id", nullable = false)
    private User user;

    // The stock in this portfolio entry, linked via a foreign key.
    // Cannot be null, as each portfolio entry must be associated with a stock.
    @ManyToOne
    @JoinColumn(name = "stock_ticker", nullable = false)
    private Stock stock;

    // Number of shares owned for this stock in the portfolio.
    // Cannot be null, as this is a required field.
    @Column(nullable = false)
    private int sharesOwned;

    // The cost basis (average purchase price per share) for the shares owned.
    // Stored as a BigDecimal for precise financial calculations, cannot be null.
    @Column(nullable = false)
    private BigDecimal costBasis;
}
