package com.PortfolioHeatmap.models;

/**
 * Represents a historical price entry for a stock in the application. This class is a JPA entity
 * mapped to the "price_history" table in the database, storing the closing price of a stock on a
 * specific date.
 * 
 * @author [Marvel Bana]
 */
import jakarta.persistence.*;
import lombok.Getter;
import lombok.Setter;
import java.time.LocalDate;

@Entity
@Getter
@Setter
@Table(name = "price_history")
public class PriceHistory {
    // Primary key for the price history entry, auto-generated by the database.
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    // The stock associated with this price history entry, linked via a foreign key.
    // Cannot be null, as each price history entry must be associated with a stock.
    @ManyToOne
    @JoinColumn(name = "stock_ticker", nullable = false)
    private Stock stock;

    // The date of this price history entry.
    // Cannot be null, as the date is a required field.
    @Column(nullable = false)
    private LocalDate date;

    // The closing price of the stock on the specified date.
    // Cannot be null, as the closing price is a required field.
    @Column(nullable = false)
    private Double closingPrice;

    @Column(name = "pe_ratio")
    private Double peRatio;

    @Column(name = "market_cap")
    private Long marketCap;
}